# Generated by Django 6.0.7 on 2026-07-08 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Condominios',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveSmallIntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida')], default='pendiente', max_length=20)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Facturas',
                'ordering': ['-anio', '-mes', 'unidad__identificador'],
            },
        ),
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='comprobantes/%Y/%m/')),
                ('monto_declarado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_declarada', models.DateField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='gestion.factura')),
            ],
            options={
                'verbose_name_plural': 'Comprobantes de pago',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50, verbose_name='Número / identificador')),
                ('renta_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='gestion.condominio')),
            ],
            options={
                'verbose_name_plural': 'Unidades',
                'ordering': ['identificador'],
                'unique_together': {('condominio', 'identificador')},
            },
        ),
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fecha_inicio_contrato', models.DateField()),
                ('unidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inquilino', to='gestion.unidad')),
            ],
            options={
                'verbose_name_plural': 'Inquilinos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='gestion.unidad'),
        ),
        migrations.AlterUniqueTogether(
            name='factura',
            unique_together={('unidad', 'mes', 'anio')},
        ),
    ]
